spring:
  application:
    name: myhr

  datasource:
    url: jdbc:h2:tcp://localhost/~/study/myhr/myhr
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        highlight_sql: true
        default_batch_fetch_size: 100
  sleuth:
    jdbc:
      p6spy:
        tracing:
          include-parameter-values: true

server:
  servlet:
    session:
      timeout: 8h

logging:
  level:
    com.lshdainty.myhr.api: debug
    com.lshdainty.myhr.repository: debug
    com.lshdainty.myhr.service: debug
    com.lshdainty.myhr.domain: debug
    p6spy: info

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true